language: generic

sudo: required
services:
  - docker

before_install:
  # running test with dev Dockerfile in client folder
  - docker build -t liamjdesmond84/react-complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true liamjdesmond84/react-complex-test npm test

# Build & Push to DockerHub
after_success: 
  # no need to specify Dockerfile because it defaults to simple Dockerfile (not Dockerfile.dev)
  - docker build -t liamjdesmond84/complex-client ./client
  - docker build -t liamjdesmond84/complex-nginx ./nginx
  - docker build -t liamjdesmond84/complex-server ./server
  - docker build -t liamjdesmond84/complex-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take build images and push them to DockerHub

  - docker push liamjdesmond84/complex-client
  - docker push liamjdesmond84/complex-nginx
  - docker push liamjdesmond84/complex-server
  - docker push liamjdesmond84/complex-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


