services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: postgres_password

    redis:
        image: redis:latest

    # /server
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            PGUSER: postgres
            PGHOST: postgres
            PGDATABASE: postgres
            PGPASSWORD: postgres_password
            PGPORT: 5432
        volumes:
            - /app/node_modules
            # Relevant to Dockerfile "/app"
            - ./server:/app

    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        environment:
            WDS_SOCKET_PORT: 0
        volumes:
            - /app/node_modules
            # Relevant to Dockerfile "/app"
            - ./client:/app

    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            # Relevant to Dockerfile "/app"
            - ./worker:/app
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379

    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            # 3050 is arbitrary if client build is going through the nginx port(3000 in this case) - browser port
            - "3050:80"
        depends_on:
            - api
            - client
